require ("lazynvim.config.fugitive")
require ("lazynvim.config.harpoon")
require ("lazynvim.config.lsp")
require ("lazynvim.config.refactoring")
require ("lazynvim.config.telescope")
require ("lazynvim.config.trouble")
require ("lazynvim.config.undotree")
require ("lazynvim.config.zenmode")
